sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn -B -T2 -fae clean install
before-caching:
  - rm -rf $HOME/.m2/repository/commons-net
notifications:
  email: false
  on_failure: never
after_success:
 - mvn clean cobertura:cobertura coveralls:report
 - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
